name: 'acticord'
description: 'Sends an entry to acticord service'
inputs:
  url:
    description: 'URL of the deployed acticord service'
    required: true
  icon:
    description: 'Repository icon'
    required: true
  state:
    description: 'Current job state [started, succeeded, failed]'
    required: true
    default: 'started'
runs:
  using: 'node16'
  main: 'dist/index.js'
